# Generated by Django 3.1.7 on 2021-04-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_auto_20210331_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negara', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='negara_id',
            field=models.IntegerField(null=True),
        ),
    ]
