# Generated by Django 3.1.7 on 2021-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0006_auto_20210401_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='negara',
        ),
        migrations.AddField(
            model_name='buku',
            name='negara_id',
            field=models.IntegerField(null=True),
        ),
    ]
